const navGroups = [
  {label:'WORKSPACE', items:[['chat','Chat','◌'],['dashboard','Dashboard','▦']]},
  {label:'CONFIGURE', items:[['roles','Agents / Roles','◇'],['models','Models','✦'],['routing','Routing','⇄'],['providers','Providers','◉'],['environment','Environment','⌂'],['projects','Projects','□'],['tools','Tools','⌘'],['memory','Memory','◒']]},
  {label:'OPERATE', items:[['jobs','Jobs','◷'],['integrations','Integrations','⊕'],['activity','Activity','≋'],['context','Context Debug','⌗'],['releases','Releases / Updates','↥'],['settings','Settings','⚙']]}
];
const nav = document.querySelector('#primary-nav');
const viewContent = document.querySelector('#view-content');
const viewTitle = document.querySelector('#view-title');
const viewKicker = document.querySelector('#view-kicker');
let currentView = 'chat';
let routeChain = [
  {provider:'Provider A', model:'Model A', health:'healthy'},
  {provider:'Provider B', model:'Model B', health:'unknown'},
  {provider:'Provider C', model:'Model C', health:'cold'}
];
const statuses = {
  healthy:['Healthy','healthy'], degraded:['Degraded','degraded'], unavailable:['Unavailable','unavailable'], disabled:['Disabled','disabled'], unknown:['Unknown','unknown'],
  warm:['Warm','healthy'], cold:['Cold','unknown'], loading:['Loading','degraded'], error:['Error','error'], not_installed:['Not installed','unavailable']
};
function statusBadge(key){const [label, cls]=statuses[key]||statuses.unknown; return `<span class="health-badge ${cls}"><span class="status-dot ${cls}"></span>${label}</span>`}
function renderNav(){nav.innerHTML=navGroups.map(group=>`<div class="nav-divider"></div><div class="section-label" style="padding:6px 11px;color:#759087">${group.label}</div>${group.items.map(([id,label,icon])=>`<button class="nav-item ${currentView===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}`).join(''); nav.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));}
function heading(eyebrow,title,lede,action=''){return `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p class="lede">${lede}</p></div>${action}</div>`}
function card(title,body,extra=''){return `<section class="card"><div class="panel-heading"><h3>${title}</h3>${extra}</div>${body}</section>`}
function chatView(){return `${heading('SECRETARY / READY','Good morning.','A clear, quiet place to ask, decide, and delegate. The secretary stays light until work needs more.','<button class="primary-button" data-action="open-wizard">Configure secretary <span>→</span></button>')}<div class="chat-layout"><section class="card chat-panel"><div class="chat-messages"><div class="message"><div class="message-avatar">V</div><div><div class="message-bubble">Good morning. I am ready on the <strong>Latency Optimized</strong> route. What would you like to work through?</div><div class="message-meta">VirtizAI · just now</div></div></div><div class="message user"><div class="message-avatar">U</div><div><div class="message-bubble">Show me what is active today.</div><div class="message-meta">You · just now</div></div></div><div class="message"><div class="message-avatar">V</div><div><div class="message-bubble">Three background jobs are active. Your secretary path is healthy and no project context was loaded for this quick check.</div><div class="message-meta">VirtizAI · 0.39 ms</div></div></div></div><div class="response-meta"><span class="meta-pill"><strong>Model</strong> Placeholder</span><span class="meta-pill"><strong>Provider</strong> Not connected</span><span class="meta-pill"><strong>Role</strong> Secretary</span><span class="meta-pill"><strong>Tokens</strong> 24 / 61 / 85</span><span class="meta-pill"><strong>Latency</strong> 0.39 ms</span><span class="meta-pill"><strong>Cost</strong> Estimate pending</span><span class="meta-pill local-mark">● Local</span><button class="details-toggle" data-action="toggle-details">Show execution details ↗</button></div><div id="execution-details" class="execution-details">Policy: secretary · Context: session only · Heavy job: not created · Telemetry: 4 stages recorded</div><div class="composer"><textarea placeholder="Ask your secretary anything..." aria-label="Message"></textarea><button class="send-button" data-action="send-message" aria-label="Send message">↑</button></div></section><aside class="chat-side"><div class="card side-card"><span class="eyebrow">ACTIVE ROUTE</span><h3 style="margin-top:7px">Latency Optimized</h3><div class="route-card"><span class="route-icon coral">1</span><span><strong>Provider A</strong><small>Model A · ${statusBadge('healthy')}</small></span></div><div class="route-card"><span class="route-icon blue">2</span><span><strong>Provider B</strong><small>Model B · ${statusBadge('unknown')}</small></span></div><button class="text-link" data-view="routing">Edit route chain →</button></div><div class="card side-card"><span class="eyebrow">COMMUNICATION</span><h3 style="margin-top:7px">Normal / Milestones / Summary</h3><p class="subtext">Your response, progress, and tool detail preferences.</p><button class="text-link" data-view="settings" style="padding-top:14px">Adjust preferences →</button></div></aside></div>`}
function dashboardView(){return `${heading('OVERVIEW','Dashboard','A calm read on the system: what is healthy, what is moving, and where attention belongs.')}<div class="grid grid-3" style="margin-bottom:16px"><div class="card stat-card"><span class="metric-label">Secretary latency</span><div class="stat-number">0.39 <small>ms</small><span class="delta">↓ 12%</span></div></div><div class="card stat-card"><span class="metric-label">Healthy providers</span><div class="stat-number">02 <small>/ 03</small></div></div><div class="card stat-card"><span class="metric-label">Jobs today</span><div class="stat-number">14 <small>completed</small></div></div></div>${card('System posture',`<div class="table-row table-head"><div>Component</div><div>Role</div><div>Status</div><div>Last check</div></div><div class="table-row"><div class="service-name"><span class="status-dot healthy"></span><div>Core API<small>SQLite / WAL</small></div></div><div>Application</div><div>${statusBadge('healthy')}</div><div class="subtext">Now</div></div><div class="table-row"><div class="service-name"><span class="status-dot healthy"></span><div>Secretary path<small>Lightweight policy</small></div></div><div>Routing</div><div>${statusBadge('healthy')}</div><div class="subtext">Now</div></div><div class="table-row"><div class="service-name"><span class="status-dot unknown"></span><div>Provider registry<small>Awaiting setup</small></div></div><div>Models</div><div>${statusBadge('unknown')}</div><div class="subtext">Not tested</div></div>`,'<button class="text-link" data-view="activity">View activity →</button>')}`}
function modelsView(){return `${heading('REGISTRY / MODELS','Models','Models are stateless execution resources. Add them through providers, then assign them to any role.','<button class="primary-button" data-action="discover-models">Discover models <span>✦</span></button>')}<div class="grid grid-2">${card('Model A',`<div class="stat-card"><div class="service-name"><span class="route-icon coral">A</span><div>Model A<small>Provider A · general reasoning</small></div><span style="margin-left:auto">${statusBadge('warm')}</span></div><div class="subtext" style="margin-top:16px">Context 32k · 0.0 estimated cost</div></div>`)}${card('Model B',`<div class="stat-card"><div class="service-name"><span class="route-icon blue">B</span><div>Model B<small>Provider B · coding</small></div><span style="margin-left:auto">${statusBadge('cold')}</span></div><div class="subtext" style="margin-top:16px">Context unknown · benchmark pending</div></div>`)}${card('Model C',`<div class="stat-card"><div class="service-name"><span class="route-icon" style="background:#9b8cb2">C</span><div>Model C<small>Provider C · deep reasoning</small></div><span style="margin-left:auto">${statusBadge('not_installed')}</span></div><div class="subtext" style="margin-top:16px">Discovery required</div></div>`)}</div>`}
function providersView(){return `${heading('REGISTRY / PROVIDERS','Providers','Keep physical location out of the application model. VirtizAI only needs reachability, capability, and health.','<button class="primary-button" data-action="add-provider">Add provider <span>+</span></button>')}<div class="card">${['Provider A|OpenAI-compatible|healthy|2 models','Provider B|Local adapter|degraded|1 model','Provider C|Cloud adapter|unknown|Not tested'].map(x=>{let [a,b,c,d]=x.split('|');return `<div class="table-row"><div class="service-name"><span class="status-dot ${statuses[c][1]}"></span><div>${a}<small>${b}</small></div></div><div>${d}</div><div>${statusBadge(c)}</div><div><button class="text-link">Test →</button></div></div>`}).join('')}</div><div class="wizard-note">Provider credentials are represented as secret references. The browser will only see Configured, Not configured, Replace secret, or Delete secret states.</div>`}
function routingView(){return `${heading('ROLES / ROUTES','Secretary routing','Choose the actual provider/model order used by the Secretary. Changes persist immediately through the shared routing API.','<button class="primary-button" data-action="add-route">Add route <span>+</span></button>')}<div class="card"><div class="panel-heading"><div><h3>Secretary — Live route</h3><span class="subtext">Only healthy eligible routes can answer</span></div><div style="display:flex;gap:8px;align-items:center"><select id="route-strategy" class="select-control"><option value="priority">Priority</option><option value="lowest_latency">Lowest latency</option><option value="cheapest_capable">Cheapest capable</option><option value="balanced">Balanced</option></select><button class="primary-button" data-action="save-route">Save route</button></div></div><div class="route-editor">${routeChain.map((r,i)=>`<div class="route-entry"><span class="route-number">${i+1}</span><div class="route-selects"><select data-route-provider="${i}" aria-label="Provider route ${i+1}"><option>${r.provider}</option></select><select data-route-model="${i}" aria-label="Model route ${i+1}"><option>${r.model}</option></select></div><button class="remove-route" data-remove-route="${i}" aria-label="Remove route">×</button></div>`).join('')}<button class="add-route" data-action="add-route">+ Add Route</button></div><div id="route-status" class="subtext" style="padding:0 19px 18px"></div></div><div class="grid grid-2" style="margin-top:16px"><div class="card stat-card"><span class="metric-label">Routing strategy</span><h3 style="margin-top:9px">Live configurable</h3><p class="subtext">Selection is persisted per role route</p></div><div class="card stat-card"><span class="metric-label">Fallback diversity</span><h3 style="margin-top:9px;color:var(--yellow)">Provider-aware</h3><p class="subtext">Warnings appear for same-provider fallback</p></div></div>`}
function settingsView(){return `${heading('SYSTEM / PREFERENCES','Settings','Communication is three separate controls: response shape, execution updates, and tool detail.','<button class="primary-button" data-action="save-settings">Save changes <span>✓</span></button>')}<div class="settings-layout"><div class="settings-nav"><button class="active">Communication</button><button>Security</button><button>Access</button><button>Updates</button></div><div class="card form-panel"><div class="form-row"><div class="form-copy"><strong>Response verbosity</strong><small>How much explanation belongs in the final answer.</small></div><div class="segmented" data-setting="response"><button class="segment">Minimal</button><button class="segment">Concise</button><button class="segment selected">Normal</button><button class="segment">Detailed</button><button class="segment">Expert</button></div></div><div class="form-row"><div class="form-copy"><strong>Execution updates</strong><small>Operational progress stays separate from conversation context.</small></div><div class="segmented" data-setting="updates"><button class="segment">Silent</button><button class="segment selected">Important milestones</button><button class="segment">Detailed</button><button class="segment">Full trace</button></div></div><div class="form-row"><div class="form-copy"><strong>Tool details</strong><small>Choose how commands and results appear in the interface.</small></div><div class="segmented" data-setting="tools"><button class="segment">Hidden</button><button class="segment selected">Summary</button><button class="segment">Commands/results</button></div></div><div class="form-row"><div class="form-copy"><strong>Secret references</strong><small>Plaintext values never return to this browser.</small></div><div class="segmented"><button class="segment selected">Configured</button><button class="segment">Replace secret</button><button class="segment">Delete secret</button></div></div></div></div>`}
function providerFormView(){return `${heading('REGISTRY / PROVIDERS','Add provider','Connect any compatible provider. For a local Ollama instance, enter the reachable base URL and discover its installed models.')}<section class="card form-panel"><div class="form-row"><div class="form-copy"><strong>Provider name</strong><small>A label for this configured endpoint. It can be anything meaningful to you.</small></div><input id="provider-name" class="select-control" placeholder="My local Ollama"></div><div class="form-row"><div class="form-copy"><strong>Adapter type</strong><small>The first real adapter in this build is Ollama. More adapters will use the same provider contract.</small></div><select id="provider-type" class="select-control"><option value="ollama">Ollama</option></select></div><div class="form-row"><div class="form-copy"><strong>Endpoint</strong><small>Base URL such as http://127.0.0.1:11434. An optional trailing /v1 is accepted and normalized.</small></div><input id="provider-endpoint" class="select-control" placeholder="http://127.0.0.1:11434"></div><div class="wizard-note">No model name is required here. VirtizAI will ask the provider for its installed models. Credentials, when needed, are stored as secret references and never returned to this form.</div><div id="provider-form-status" class="subtext" style="margin-top:16px"></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:22px"><button class="quiet-button" data-view="providers">Cancel</button><button class="primary-button" data-action="save-provider">Save and discover models <span>→</span></button></div></section>`}
function genericView(name, kicker, text){return `${heading(kicker,name,text,'<button class="primary-button" data-action="placeholder-action">Add <span>+</span></button>')}<div class="card" style="padding:38px;text-align:center"><span class="route-icon coral" style="margin:0 auto 14px">V</span><h2>${name} registry ready</h2><p class="lede" style="margin:8px auto">The core API boundary is in place. This surface will become fully data-backed in the next capability phase.</p><button class="quiet-button" data-action="open-wizard" style="margin-top:20px">Review setup</button></div>`}
function toolsView(){return `${heading('EXECUTION / TOOLS','Tools','Typed tools run through supervised workers with explicit permissions, drivers, and limits.')}<div id="tools-list" class="grid grid-2"><div class="card stat-card">Loading tool definitions…</div></div>`}
function jobsView(){return `${heading('OPERATE / JOBS','Jobs','Execution stays independent from the secretary and can be cancelled without dropping the session.')}<div id="jobs-list" class="card"><div class="table-row table-head"><div>Job</div><div>Status</div><div>Tool</div><div>Driver</div></div></div>`}
function activityView(){return `${heading('OPERATE / AUDIT','Activity','Execution telemetry and authorization decisions stay out of conversational history.')}<div id="activity-list" class="card"><div class="table-row table-head"><div>Tool</div><div>Driver</div><div>Authorization</div><div>Result</div></div></div>`}
function liveDashboardView(data){const providers=data.providers||{};const jobs=data.jobs||{};const healthy=providers.healthy||0;const providerTotal=Object.values(providers).reduce((sum,value)=>sum+value,0);const jobTotal=Object.values(jobs).reduce((sum,value)=>sum+value,0);const latency=data.secretary_latency_ms==null?'No responses yet':`${Number(data.secretary_latency_ms).toFixed(2)} ms`;const activity=data.recent_activity||[];const p50=data.secretary_latency_p50_ms==null?'—':`${Number(data.secretary_latency_p50_ms).toFixed(2)} ms`;const p95=data.secretary_latency_p95_ms==null?'—':`${Number(data.secretary_latency_p95_ms).toFixed(2)} ms`;return `${heading('OVERVIEW','Dashboard','Live operational state from VirtizAI telemetry, provider health, jobs, and execution audit.')}<div class="grid grid-3" style="margin-bottom:16px"><div class="card stat-card"><span class="metric-label">Secretary latency</span><div class="stat-number">${latency}</div><div class="subtext">p50 ${p50} · p95 ${p95} · ${data.secretary_response_count||0} responses</div></div><div class="card stat-card"><span class="metric-label">Healthy providers</span><div class="stat-number">${healthy} <small>/ ${providerTotal}</small></div><div class="subtext">Live registry health</div></div><div class="card stat-card"><span class="metric-label">Jobs recorded</span><div class="stat-number">${jobTotal}</div><div class="subtext">Persisted job states</div></div></div>${card('System posture',`<div class="table-row table-head"><div>Component</div><div>Role</div><div>Status</div><div>Measured</div></div><div class="table-row"><div class="service-name"><span class="status-dot healthy"></span><div>Core API<small>SQLite / WAL</small></div></div><div>Application</div><div>${statusBadge('healthy')}</div><div class="subtext">Live</div></div><div class="table-row"><div class="service-name"><span class="status-dot ${data.secretary_response_count?'healthy':'unknown'}"></span><div>Secretary path<small>Persisted assistant latency</small></div></div><div>Routing</div><div>${statusBadge(data.secretary_response_count?'healthy':'unknown')}</div><div class="subtext">${latency}</div></div><div class="table-row"><div class="service-name"><span class="status-dot ${healthy?'healthy':'unknown'}"></span><div>Provider registry<small>${providerTotal} configured</small></div></div><div>Models</div><div>${statusBadge(healthy?'healthy':'unknown')}</div><div class="subtext">Live</div></div>`,'<button class="text-link" data-view="activity">View activity →</button>')}<div class="card" style="margin-top:16px"><div class="panel-heading"><h3>Recent execution activity</h3></div>${activity.length?activity.map(item=>`<div class="table-row"><div>${item.tool_id||'Unknown tool'}</div><div>${item.driver}</div><div>${item.authorization}</div><div>${JSON.parse(item.result_json||'{}').status||'Recorded'}</div></div>`).join(''):'<div class="stat-card">No execution activity recorded yet.</div>'}</div>`}
function environmentView(){return `${heading('REGISTRY / ENVIRONMENTS','Environment','Canonical hosts, services, addresses, and access references live here. They are retrieved only when relevant.','<button class="primary-button" data-action="add-environment">Add environment <span>+</span></button>')}<div id="environment-list" class="card"><div class="table-row table-head"><div>Name</div><div>Type</div><div>Address</div><div>Status</div></div></div>`}
function projectsView(){return `${heading('REGISTRY / PROJECTS','Projects','Project metadata, context sources, and relevant environments stay scoped to the active project.','<button class="primary-button" data-action="add-project">Add project <span>+</span></button>')}<div id="project-list" class="grid grid-2"></div>`}
function memoryView(){return `${heading('STATE / MEMORY','Memory','Durable memory is intentional, scoped, and provenance-aware. Scratch and telemetry are excluded.','<button class="primary-button" data-action="add-memory">Remember a fact <span>+</span></button>')}<div id="memory-list" class="card"></div>`}
function contextView(){return `${heading('DEBUG / CONTEXT','Context inspection','Inspect exactly what the broker selected, its token composition, and what it omitted.')}<div class="card form-panel"><div class="form-row"><div class="form-copy"><strong>Context build</strong><small>Preview uses a session-only secretary budget and does not call a model.</small></div><button class="primary-button" data-action="preview-context">Build preview <span>→</span></button></div><pre id="context-preview" class="execution-details" style="display:block;white-space:pre-wrap">No context build selected.</pre></div>`}
function discordView(){return `${heading('INTERFACE / DISCORD','Discord','Discord runs as an in-process adapter over the same sessions, routing, context, tools, and jobs.')}<section class="card form-panel"><div class="form-row"><div class="form-copy"><strong>Connection mode</strong><small>Use an existing bot or follow guided creation instructions.</small></div><select id="discord-mode" class="select-control"><option value="existing_bot">I already have a Discord bot</option><option value="guided">Help me create one</option></select></div><div class="form-row"><div class="form-copy"><strong>Bot secret reference</strong><small>Only a reference is stored. The token is never returned to this browser.</small></div><input id="discord-secret-ref" class="select-control" placeholder="Secret reference name"></div><div class="form-row"><div class="form-copy"><strong>ReleaseNotes channel</strong><small>Optional channel ID for future release events.</small></div><input id="discord-release-channel" class="select-control" placeholder="Channel ID (optional)"></div><div class="form-row"><div class="form-copy"><strong>Permissions</strong><small>Admin users/roles are explicit mappings, never inferred from usernames.</small></div><input id="discord-admin-users" class="select-control" placeholder="Allowed admin user IDs"></div><div id="discord-status" class="subtext"></div><div style="display:flex;justify-content:flex-end;margin-top:20px"><button class="primary-button" data-action="save-discord">Save Discord configuration <span>✓</span></button></div></section>`}
const views={chat:chatView,dashboard:dashboardView,models:modelsView,providers:providersView,routing:routingView,settings:settingsView,roles:()=>genericView('Agents / Roles','REGISTRY / ROLES','Give each role a clear purpose and needs, without tying it to a particular model.'),environment:environmentView,projects:projectsView,tools:toolsView,memory:memoryView,jobs:jobsView,integrations:discordView,activity:activityView,releases:()=>genericView('Releases / Updates','SYSTEM / RELEASES','Updates and rollback are coordinated by one Update Manager.'),context:contextView};
function showView(view){currentView=view;renderNav();viewContent.innerHTML=(views[view]||views.dashboard)();viewTitle.textContent=({chat:'Chat',dashboard:'Dashboard',roles:'Agents / Roles',models:'Models',routing:'Routing',providers:'Providers',environment:'Environment',projects:'Projects',tools:'Tools',memory:'Memory',jobs:'Jobs',integrations:'Integrations',activity:'Activity',releases:'Releases / Updates',settings:'Settings'})[view]||'Workspace';viewKicker.textContent=view==='chat'?'Secretary':'Workspace';bindViewActions();if(view==='chat')clearChatDemo();refreshLiveData(view);}
function clearChatDemo(){const messages=document.querySelector('.chat-messages');if(messages)messages.innerHTML='<div class="stat-card" style="margin:auto;text-align:center;color:var(--muted)">No conversation yet. Your first response will show live provider, model, token, latency, and cost metadata here.</div>';const pills=document.querySelectorAll('.response-meta .meta-pill');if(pills.length>=6){pills[0].innerHTML='<strong>Model</strong> No response yet';pills[1].innerHTML='<strong>Provider</strong> No response yet';pills[3].innerHTML='<strong>Tokens</strong> — / — / —';pills[4].innerHTML='<strong>Latency</strong> —';pills[5].innerHTML='<strong>Cost</strong> —';}}
function bindViewActions(){viewContent.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.view)));viewContent.querySelectorAll('[data-remove-route]').forEach(el=>el.addEventListener('click',()=>{routeChain.splice(Number(el.dataset.removeRoute),1);showView('routing')}));viewContent.querySelectorAll('.segment').forEach(el=>el.addEventListener('click',()=>{el.parentElement.querySelectorAll('.segment').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}));viewContent.querySelectorAll('[data-action]').forEach(bindAction);}
let liveSessionId=null;
let liveRouteId=null;
async function sendLiveMessage(text){
  appendChatMessage('user', text, 'You · just now');
  appendChatMessage('assistant', 'Working on it…', 'VirtizAI · waiting for provider');
  const result=await fetch('/v1/interfaces/message',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({interface_type:'webui',external_subject:'webui-user',content:text,session_id:liveSessionId})}).then(response=>{if(!response.ok)throw new Error(`Request failed (${response.status})`);return response.json()});
  liveSessionId=result.session_id;
  const pending=document.querySelector('.message.pending');if(pending){pending.classList.remove('pending');pending.querySelector('.message-bubble').textContent=result.content;pending.querySelector('.message-meta').textContent=`VirtizAI · ${(result.latency_ms||0).toFixed(2)} ms`;}
  const pills=document.querySelectorAll('.response-meta .meta-pill');
  if(pills.length>=6){pills[0].innerHTML=`<strong>Model</strong> ${result.model_name||result.model_id||'Unavailable'}`;pills[1].innerHTML=`<strong>Provider</strong> ${result.provider_name||result.provider_id||'Unavailable'}`;pills[3].innerHTML=`<strong>Tokens</strong> ${result.input_tokens??'—'} / ${result.output_tokens??'—'} / ${result.total_tokens??'—'}`;pills[4].innerHTML=`<strong>Total latency</strong> ${(result.latency_ms||0).toFixed(2)} ms`;pills[5].innerHTML=`<strong>Cost</strong> ${result.estimated_cost??'Not available'}`;}
  document.querySelector('#execution-details').textContent=`Route: ${result.route_id||'none'} · Provider: ${result.provider_id||'none'} · Exact usage: ${result.usage_exact?'yes':'no'} · Heavy job: ${result.job_created?'created':'not created'}`;
  fetch('/v1/dashboard').then(response=>response.json()).then(updateInspector).catch(()=>{});
}
function appendChatMessage(role,content,meta){const messages=document.querySelector('.chat-messages');if(!messages)return;const empty=messages.querySelector('.stat-card');if(empty)empty.remove();const item=document.createElement('div');item.className=`message ${role==='user'?'user':''} ${role==='assistant'&&content==='Working on it…'?'pending':''}`;item.innerHTML=`<div class="message-avatar">${role==='user'?'U':'V'}</div><div><div class="message-bubble"></div><div class="message-meta"></div></div>`;item.querySelector('.message-bubble').textContent=content;item.querySelector('.message-meta').textContent=meta;messages.appendChild(item);messages.scrollTop=messages.scrollHeight;}
async function saveProvider(){const status=document.querySelector('#provider-form-status');const name=document.querySelector('#provider-name').value.trim();const adapter_type=document.querySelector('#provider-type').value;const endpoint=document.querySelector('#provider-endpoint').value.trim();if(!name||!endpoint){status.textContent='Provider name and endpoint are required.';return}status.textContent='Saving provider and checking endpoint…';try{const created=await fetch('/v1/providers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,adapter_type,endpoint})}).then(response=>{if(!response.ok)throw new Error('Provider could not be created');return response.json()});const health=await fetch(`/v1/providers/${created.id}/health`,{method:'POST'}).then(response=>response.json());if(health.state==='healthy')await fetch(`/v1/providers/${created.id}/discover`,{method:'POST'});showView('providers')}catch(error){status.textContent=error.message+' Check the endpoint and try again.'}}
function dataFormView(kind){const labels={project:['Add project','Project name','Description','Local path'],environment:['Add environment','Display name','Target type','Address'],memory:['Remember a fact','Memory text','Namespace','Source reference']};const [title,first,second,third]=labels[kind];return `${heading('STRUCTURED DATA',title,'Create canonical state without editing YAML or markdown.')}<section class="card form-panel"><div class="wizard-field"><label>${first}</label><input id="data-first" class="select-control" placeholder="${first}"></div><div class="wizard-field"><label>${second}</label><input id="data-second" class="select-control" placeholder="${second}"></div><div class="wizard-field"><label>${third}</label><input id="data-third" class="select-control" placeholder="${third}"></div><div id="data-form-status" class="subtext"></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:22px"><button class="quiet-button" data-view="${kind==='project'?'projects':kind==='environment'?'environment':'memory'}">Cancel</button><button class="primary-button" data-action="save-${kind}">Save <span>✓</span></button></div></section>`}
async function saveDiscord(){const status=document.querySelector('#discord-status');const response=await fetch('/v1/discord/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:true,mode:document.querySelector('#discord-mode').value,bot_secret_ref:document.querySelector('#discord-secret-ref').value||null,release_channel_id:document.querySelector('#discord-release-channel').value||null,admin_users:(document.querySelector('#discord-admin-users').value||'').split(',').map(value=>value.trim()).filter(Boolean)})});status.textContent=response.ok?'Saved. Secret status is preserved without returning its value.':'Could not save Discord configuration.'}
async function saveRoute(){const status=document.querySelector('#route-status');if(!liveRouteId){if(status)status.textContent='No persisted Secretary route is available yet.';return}const targets=[...document.querySelectorAll('[data-route-provider]')].map((providerSelect,index)=>({provider_id:providerSelect.value,model_id:document.querySelector(`[data-route-model="${index}"]`).value,ordinal:index}));const response=await fetch(`/v1/routes/${liveRouteId}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({strategy:document.querySelector('#route-strategy').value,targets})});if(status)status.textContent=response.ok?'Saved. Secretary will use the new eligible order on the next request.':'Could not save route changes.';if(response.ok)showView('routing')}
async function saveStructured(kind){const first=document.querySelector('#data-first').value.trim();const second=document.querySelector('#data-second').value.trim();const third=document.querySelector('#data-third').value.trim();const status=document.querySelector('#data-form-status');if(!first){status.textContent='A name or content value is required.';return}let endpoint,payload,next;if(kind==='project'){endpoint='/v1/projects';payload={name:first,description:second||null,root_path:third||null};next='projects'}else if(kind==='environment'){endpoint='/v1/environments';payload={name:first,target_type:second||'local',address:third||null};next='environment'}else{endpoint='/v1/memory';payload={content:first,namespace:second||'global',source_ref:third||null,user_id:'webui-user'};next='memory'}const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){status.textContent='Could not save this record.';return}showView(next)}
async function previewContext(){const session=await fetch('/v1/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({user_id:'webui-user'})}).then(response=>response.json());const result=await fetch(`/v1/context?user_id=webui-user&session_id=${session.session_id}&sources=conversation,memory,project,environment`).then(response=>response.json());document.querySelector('#context-preview').textContent=JSON.stringify(result,null,2)}
function bindAction(el){el.addEventListener('click',()=>{const action=el.dataset.action;if(action==='close-wizard'){closeWizard();return}if(action==='wizard-back'||action==='wizard-next'){wizardAction(action);return}if(action==='open-wizard')openWizard();if(action==='open-settings')showView('settings');if(action==='toggle-details')document.querySelector('#execution-details')?.classList.toggle('open');if(action==='save-provider'){saveProvider();return}if(action==='save-discord'){saveDiscord();return}if(action==='save-route'){saveRoute();return}if(action==='preview-context'){previewContext();return}if(action==='save-project'||action==='save-environment'||action==='save-memory'){saveStructured(action.replace('save-',''));return}if(action==='send-message'){const textarea=document.querySelector('.composer textarea');if(textarea.value.trim()){const text=textarea.value.trim();textarea.value='';sendLiveMessage(text).catch(error=>{const pending=document.querySelector('.message.pending');if(pending){pending.classList.remove('pending');pending.querySelector('.message-bubble').textContent=`Unable to get a response: ${error.message}`;pending.querySelector('.message-meta').textContent='VirtizAI · request failed';}});el.animate([{transform:'scale(1)'},{transform:'scale(.9)'},{transform:'scale(1)'}],{duration:220})}}if(action==='add-route'){routeChain.push({provider:'Provider '+String.fromCharCode(65+routeChain.length),model:'Model '+String.fromCharCode(65+routeChain.length),health:'unknown'});showView('routing')}if(action==='add-provider'){viewContent.innerHTML=providerFormView();bindViewActions();}if(action==='add-project'||action==='add-environment'||action==='add-memory'){viewContent.innerHTML=dataFormView(action.replace('add-',''));bindViewActions();}if(action==='discover-models'||action==='placeholder-action')openWizard()})}
function openWizard(){wizard.classList.remove('hidden');wizard.setAttribute('aria-hidden','false');wizardStep=0;renderWizard();}
function closeWizard(){wizard.classList.add('hidden');wizard.setAttribute('aria-hidden','true');}
const wizard=document.querySelector('#wizard');let wizardStep=0;const wizardNames=['Admin setup','Interface selection','Secretary route','Model benchmark','Discord','Providers','Environments','Projects & files','External URL','Validation','Finish'];
const wizardBodies=[
['Name your workspace','This identity stays local and can be changed later.','<div class="wizard-field"><label>Workspace name</label><input value="My VirtizAI" aria-label="Workspace name"></div><div class="wizard-field"><label>Admin display name</label><input value="Admin" aria-label="Admin display name"></div>'],
['Choose your first interfaces','All interfaces share the same core API, sessions, and configuration.','<div class="wizard-grid"><button class="choice-card selected"><strong>WebUI</strong><small>Chat and administration in the browser.</small></button><button class="choice-card selected"><strong>CLI</strong><small>Full terminal administration and chat.</small></button><button class="choice-card"><strong>Discord</strong><small>Optional remote conversational access.</small></button></div>'],
['Shape your secretary route','Start with a route chain, not a single model. You can add providers later.','<div class="card route-editor"><div class="route-entry"><span class="route-number">1</span><div class="route-selects"><select aria-label="Secretary provider"><option>Provider A</option><option>Provider B</option><option>Provider C</option></select><select aria-label="Secretary model"><option>Model A</option><option>Model B</option><option>Model C</option></select></div></div><button class="add-route">+ Add Route</button></div><div class="wizard-note">Demo providers and models are shown for this test build. Add and discover real providers in the later provider configuration phase.</div>'],
['Benchmark is optional','You can benchmark eligible models now or skip and configure routes later.','<div class="wizard-grid"><button class="choice-card selected"><strong>Skip for now</strong><small>Use health and capability metadata as it becomes available.</small></button><button class="choice-card"><strong>Run benchmark</strong><small>Measure latency and output quality for selected models.</small></button></div>'],
['Connect Discord when ready','This is optional. Existing bot credentials are stored as secret references only.','<div class="wizard-grid"><button class="choice-card selected"><strong>Not now</strong><small>Continue with LAN-only WebUI and CLI.</small></button><button class="choice-card"><strong>I already have a bot</strong><small>Discover servers and channels after authentication.</small></button><button class="choice-card"><strong>Help me create one</strong><small>Show Developer Portal settings and intents.</small></button></div>'],
['Add providers','Provider endpoints and credential fields are configured in the product.','<div class="wizard-field"><label>Provider name</label><input placeholder="e.g. Fast local provider"></div><div class="wizard-field"><label>Adapter type</label><select><option>Choose adapter</option><option>OpenAI-compatible</option><option>Native provider</option></select></div><div class="wizard-note">API keys show only as Not configured or Configured. Plaintext is never returned after save.</div>'],
['Register environments','Keep execution targets optional and capability-driven.','<div class="wizard-grid"><button class="choice-card selected"><strong>This machine</strong><small>Use a bounded local workspace for initial jobs.</small></button><button class="choice-card"><strong>Remote target</strong><small>Add a reachable SSH/API environment later.</small></button></div>'],
['Add projects and files','Projects are metadata and references. Job workspaces stay disposable.','<div class="wizard-field"><label>Project name (optional)</label><input placeholder="e.g. Product workspace"></div><div class="wizard-field"><label>Project root (optional)</label><input placeholder="/path/to/project"></div>'],
['Keep access local by default','External access is optional and does not require registrar or proxy ownership.','<div class="wizard-grid"><button class="choice-card selected"><strong>LAN only</strong><small>Listen locally and use Discord remotely if configured.</small></button><button class="choice-card"><strong>External URL</strong><small>Add proxy mode and trusted forwarded header settings.</small></button></div>'],
['Validate connectivity','Run safe checks before finishing. No production environment is touched by this setup.','<div class="card stat-card"><div class="status-pair"><span class="status-dot healthy"></span><strong>Core database</strong><span style="margin-left:auto">Ready</span></div><div class="status-pair" style="margin-top:14px"><span class="status-dot unknown"></span><strong>Provider registry</strong><span style="margin-left:auto">Not configured</span></div><div class="status-pair" style="margin-top:14px"><span class="status-dot unknown"></span><strong>External URL</strong><span style="margin-left:auto">Skipped</span></div></div>'],
['You are ready to explore','Your core is configured. Add providers and refine routes whenever you are ready.','<div class="wizard-note" style="border-color:var(--green)">VirtizAI is ready. The secretary path remains lightweight until you explicitly delegate work.</div>']
];
function renderWizard(){document.querySelector('#wizard-count').textContent=`Step ${wizardStep+1} of ${wizardNames.length}`;document.querySelector('#wizard-steps').innerHTML=wizardNames.map((name,i)=>`<div class="wizard-step ${i===wizardStep?'current':''} ${i<wizardStep?'done':''}"><span>${i<wizardStep?'✓':i+1}</span>${name}</div>`).join('');const [title,lede,body]=wizardBodies[wizardStep];document.querySelector('#wizard-content').innerHTML=`<span class="eyebrow">${wizardNames[wizardStep].toUpperCase()}</span><h2>${title}</h2><p class="lede">${lede}</p>${body}`;document.querySelector('[data-action="wizard-back"]').style.visibility=wizardStep===0?'hidden':'visible';document.querySelector('[data-action="wizard-next"]').innerHTML=wizardStep===wizardNames.length-1?'Finish <span>✓</span>':'Continue <span>→</span>';}
function wizardAction(action){if(action==='wizard-back'&&wizardStep>0){wizardStep--;renderWizard()}if(action==='wizard-next'){if(wizardStep<wizardNames.length-1){wizardStep++;renderWizard()}else closeWizard()}}
async function loadReleasesView(){
  const data=await fetch('/v1/releases').then(response=>response.json());
  const releases=data.releases||[];
  viewContent.innerHTML=`${heading('SYSTEM / RELEASES','Releases / Updates','Release metadata, policy, and history are shared by WebUI, Discord, and CLI. Privileged installs run outside the application.')}<section class="card"><div class="panel-heading"><h3>Update policy</h3><button id="check-updates" class="primary-button">Check updates <span>↥</span></button></div><p class="subtext">Channel: ${data.policy.channel} · Policy: ${data.policy.version_policy}${data.policy.pinned_version?` · Pinned: ${data.policy.pinned_version}`:''}</p><div id="release-plan" class="wizard-note">No update check has run.</div></section><section class="card" style="margin-top:16px"><div class="panel-heading"><h3>Known releases</h3></div>${releases.length?releases.map(item=>`<div class="table-row"><div>${item.version}</div><div>${item.channel}</div><div>${item.release_url}</div></div>`).join(''):'<p class="subtext">No release manifests imported yet.</p>'}</section>`;
  document.querySelector('#check-updates').addEventListener('click',async()=>{const plan=await fetch('/v1/updates/plan?platform=debian-amd64').then(response=>response.json());document.querySelector('#release-plan').textContent=plan.available?`Verified update available: ${plan.release.version}. Apply it with the platform updater helper or your external deployment tool.`:'No verified update is available for this platform and policy.'});
}
const baseShowView=showView;
showView=function(view){baseShowView(view);if(view==='releases')loadReleasesView().catch(()=>{viewContent.innerHTML=genericView('Releases / Updates','SYSTEM / RELEASES','Release metadata is unavailable.');});};
document.querySelectorAll('[data-action]').forEach(bindAction);
renderNav();showView('chat');
if(new URLSearchParams(location.search).get('wizard')==='1')openWizard();
fetch('/healthz').then(response=>response.ok?response.json():null).then(health=>{
  if(!health)return;
  document.querySelectorAll('.build-tag').forEach(el=>el.textContent=`VirtizAI ${health.version}`);
  document.querySelectorAll('.wizard-foot').forEach(el=>el.innerHTML=`<span class="status-dot healthy"></span> Core ready · schema v${health.schema_version}`);
}).catch(()=>{});

async function refreshLiveData(view){
  if(view==='dashboard'){
    try{const data=await fetch('/v1/dashboard').then(response=>response.json());viewContent.innerHTML=liveDashboardView(data);bindViewActions();updateInspector(data);}catch(error){console.debug('Dashboard data unavailable',error)}
    return;
  }
  if(!['chat','providers','models','routing','tools','jobs','activity','environment','projects','memory'].includes(view))return;
  try{
    const [providerResponse,modelResponse]=await Promise.all([fetch('/v1/providers'),fetch('/v1/models')]);
    const providers=await providerResponse.json();
    const models=await modelResponse.json();
    if(view==='providers' && providers.length){
      const rows=providers.map(provider=>`<div class="table-row"><div class="service-name"><span class="status-dot ${provider.health_status}"></span><div>${provider.name}<small>${provider.adapter_type} · ${provider.endpoint||'isolated/local'}</small></div></div><div>${models.filter(model=>model.provider_id===provider.id).length} models</div><div>${statusBadge(provider.health_status)}</div><div><button class="text-link" data-provider-health="${provider.id}">Check →</button></div></div>`).join('');
      const panel=viewContent.querySelector('.card'); if(panel)panel.innerHTML=rows;
    }
    if(view==='models' && models.length){
      const html=models.map(model=>`<div class="card stat-card"><div class="service-name"><span class="route-icon coral">M</span><div>${model.name}<small>${model.provider_name} · ${model.locality||'capability metadata pending'}</small></div><span style="margin-left:auto">${statusBadge(model.status)}</span></div><div class="subtext" style="margin-top:16px">${model.context_window?`Context ${model.context_window}`:'Context unknown'} · discovered live</div></div>`).join('');
      const grid=viewContent.querySelector('.grid'); if(grid)grid.innerHTML=html;
    }
    if(view==='routing'){
      const routes=await fetch('/v1/routes').then(response=>response.json());
      if(routes.length){
        liveRouteId=routes[0].id;
        const eligibility=await fetch(`/v1/routes/${routes[0].id}/eligibility`).then(response=>response.json());
        const editor=viewContent.querySelector('.route-editor');
        const providerOptions=providers.map(provider=>`<option value="${provider.id}">${provider.name}</option>`).join('');
        if(editor){editor.innerHTML=eligibility.routes.map((route,index)=>`<div class="route-entry"><span class="route-number">${index+1}</span><div class="route-selects"><select data-route-provider="${index}" aria-label="Live provider route ${index+1}">${providers.map(provider=>`<option value="${provider.id}" ${provider.id===route.provider_id?'selected':''}>${provider.name}</option>`).join('')}</select><select data-route-model="${index}" aria-label="Live model route ${index+1}">${models.map(model=>`<option value="${model.id}" ${model.id===route.model_id?'selected':''}>${model.provider_name} / ${model.name}</option>`).join('')}</select></div><span class="status-pair"><span class="status-dot healthy"></span>Eligible</span></div>`).join('')+'<div class="wizard-note">'+(eligibility.warnings[0]||'Provider-diverse fallback chain · live eligibility')+'</div>';}
        const routeHeading=viewContent.querySelector('.panel-heading h3'); if(routeHeading)routeHeading.textContent=routes[0].name;
        const strategySelect=viewContent.querySelector('#route-strategy'); if(strategySelect){try{strategySelect.value=JSON.parse(routes[0].policy_json||'{}').strategy||'priority';}catch(error){strategySelect.value='priority';}}
      }
    }
    if(view==='chat'){
      const routes=await fetch('/v1/routes').then(response=>response.json());
      const side=viewContent.querySelector('.chat-side .side-card');
      if(side&&routes.length){const eligibility=await fetch(`/v1/routes/${routes[0].id}/eligibility`).then(response=>response.json());side.innerHTML=`<span class="eyebrow">ACTIVE ROUTE</span><h3 style="margin-top:7px">${routes[0].name}</h3>${eligibility.routes.slice(0,3).map((route,index)=>`<div class="route-card"><span class="route-icon ${index?'blue':'coral'}">${index+1}</span><span><strong>${route.provider_name}</strong><small>${route.model_name} · ${statusBadge('healthy')}</small></span></div>`).join('')}<button class="text-link" data-view="routing">Edit route chain →</button>`;side.querySelector('[data-view]')?.addEventListener('click',()=>showView('routing'));}
    }
    if(view==='tools'){
      const tools=await fetch('/v1/tools').then(response=>response.json());
      const list=viewContent.querySelector('#tools-list'); if(list)list.innerHTML=tools.map(tool=>`<div class="card stat-card"><div class="service-name"><span class="route-icon coral">⌘</span><div>${tool.display_name}<small>${tool.name} · ${tool.description}</small></div></div><div class="subtext" style="margin-top:14px">Permissions: ${tool.required_permissions.join(', ')} · Drivers: ${tool.allowed_drivers.join(', ')}</div><button class="text-link" data-tool-run="${tool.name}" style="margin-top:12px">Run safe demo →</button></div>`).join('');
    }
    if(view==='jobs'){
      const jobs=await fetch('/v1/jobs').then(response=>response.json());
      const list=viewContent.querySelector('#jobs-list'); if(list)list.innerHTML='<div class="table-row table-head"><div>Job</div><div>Status</div><div>Tool</div><div>Driver</div></div>'+jobs.map(job=>`<div class="table-row"><div class="service-name">${job.id}<small>${job.created_at||''}</small></div><div>${job.status}</div><div>${job.kind}</div><div>${job.result_json?'local':'queued'}</div></div>`).join('');
    }
    if(view==='activity'){
      const events=await fetch('/v1/activity').then(response=>response.json());
      const list=viewContent.querySelector('#activity-list'); if(list)list.innerHTML='<div class="table-row table-head"><div>Tool</div><div>Driver</div><div>Authorization</div><div>Result</div></div>'+events.map(event=>`<div class="table-row"><div>${event.tool_id||'unknown'}</div><div>${event.driver}</div><div>${event.authorization}</div><div>${JSON.parse(event.result_json||'{}').status||'recorded'}</div></div>`).join('');
    }
    if(view==='environment'){
      const items=await fetch('/v1/environments').then(response=>response.json());
      const list=viewContent.querySelector('#environment-list'); if(list)list.innerHTML='<div class="table-row table-head"><div>Name</div><div>Type</div><div>Address</div><div>Status</div></div>'+items.map(item=>`<div class="table-row"><div class="service-name">${item.name}<small>${item.tags||'canonical target'}</small></div><div>${item.target_type}</div><div>${item.address||'local'}</div><div>${statusBadge(item.health_status)}</div></div>`).join('');
    }
    if(view==='projects'){
      const items=await fetch('/v1/projects').then(response=>response.json());
      const list=viewContent.querySelector('#project-list'); if(list)list.innerHTML=items.map(item=>`<div class="card stat-card"><h3>${item.name}</h3><p class="subtext">${item.description||'No description'} · ${item.root_path||'No local path'}</p></div>`).join('')||'<div class="card stat-card">No projects registered.</div>';
    }
    if(view==='memory'){
      const items=await fetch('/v1/memory').then(response=>response.json());
      const list=viewContent.querySelector('#memory-list'); if(list)list.innerHTML=items.map(item=>`<div class="table-row"><div>${item.namespace}</div><div>${item.content}</div><div>${item.source_ref||'manual'}</div><div>${item.verified_state||'unverified'}</div></div>`).join('')||'<div class="stat-card">No durable memory registered.</div>';
    }
    viewContent.querySelectorAll('[data-provider-health]').forEach(button=>button.addEventListener('click',async()=>{await fetch(`/v1/providers/${button.dataset.providerHealth}/health`,{method:'POST'});showView('providers')}));
    viewContent.querySelectorAll('[data-tool-run]').forEach(button=>button.addEventListener('click',async()=>{button.textContent='Running…';await fetch('/v1/tools/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tool:button.dataset.toolRun,profile:'general'})});button.textContent='Queued · refresh Jobs →'}));
  }catch(error){console.debug('Live registry refresh unavailable',error)}
}
function updateInspector(data){const blocks=document.querySelectorAll('.inspector .metric-block');const latency=data.secretary_latency_ms==null?'No data':`${Number(data.secretary_latency_ms).toFixed(2)} ms`;const jobs=Object.values(data.jobs||{}).reduce((sum,value)=>sum+value,0);if(blocks[0]){blocks[0].querySelector('strong').textContent=latency;blocks[0].querySelector('small').textContent=`${data.secretary_response_count||0} measured responses`;}if(blocks[1]){blocks[1].querySelector('.metric-label').textContent='Jobs recorded';blocks[1].querySelector('strong').textContent=String(jobs).padStart(2,'0');blocks[1].querySelector('small').textContent=`${data.jobs?.running||0} running · ${data.jobs?.queued||0} queued`;blocks[1].style.cursor='pointer';blocks[1].title='Open Jobs';blocks[1].onclick=()=>showView('jobs');}const recent=document.querySelector('.inspector .recent');if(recent){const activity=data.recent_activity||[];recent.innerHTML='<div class="section-label">Recent activity</div>'+(activity.length?activity.slice(0,2).map(item=>`<div class="activity-line"><div><strong>${item.tool_id||'Execution event'}</strong><small>${item.driver} · ${JSON.parse(item.result_json||'{}').status||'recorded'}</small></div></div>`).join(''):'<div class="activity-line"><div><strong>No activity yet</strong><small>Live execution events appear here</small></div></div>');}}
