name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: ./.github/workflows/release-build.yml
    with:
      publish_image: true
      publish_release: true
      channel: beta
    secrets: inherit
